
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StreetFighterGame
{

using System;
    using System.Collections.Generic;
    
public partial class LICH_SU_TRAN_DAU
{

    public int TranDauId { get; set; }

    public int UserId { get; set; }

    public int NhanVat1Id { get; set; }

    public int NhanVat2Id { get; set; }

    public string KetQua { get; set; }

    public Nullable<System.DateTime> ThoiGianTranDau { get; set; }



    public virtual NHAN_VAT NHAN_VAT { get; set; }

    public virtual NHAN_VAT NHAN_VAT1 { get; set; }

    public virtual TAI_KHOAN TAI_KHOAN { get; set; }

}

}
