
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StreetFighterGame
{

using System;
    using System.Collections.Generic;
    
public partial class NHAN_VAT
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NHAN_VAT()
    {

        this.LICH_SU_TRAN_DAU = new HashSet<LICH_SU_TRAN_DAU>();

        this.LICH_SU_TRAN_DAU1 = new HashSet<LICH_SU_TRAN_DAU>();

    }


    public int NhanVatId { get; set; }

    public string TenNhanVat { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LICH_SU_TRAN_DAU> LICH_SU_TRAN_DAU { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LICH_SU_TRAN_DAU> LICH_SU_TRAN_DAU1 { get; set; }

}

}
