
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace StreetFighterGame
{

using System;
    using System.Collections.Generic;
    
public partial class XEP_HANG
{

    public int UserId { get; set; }

    public int SoTranThang { get; set; }

    public int XepHang { get; set; }



    public virtual TAI_KHOAN TAI_KHOAN { get; set; }

}

}
